### ISSUE TITLE
Release v0.4.0

### ISSUE THREAD

**Issue by jrriehl** [fetchai/jenesis#105]
- [x] https://github.com/fetchai/jenesis/issues/104
- [x] https://github.com/fetchai/jenesis/issues/98
- [x] https://github.com/fetchai/jenesis/issues/99
- [x] https://github.com/fetchai/jenesis/issues/97
- [x] https://github.com/fetchai/jenesis/issues/101
- [x] https://github.com/fetchai/jenesis/issues/102
- [x] https://github.com/fetchai/jenesis/issues/100
