### ISSUE TITLE
Release v0.1.0

### ISSUE THREAD

**Issue by jrriehl** [fetchai/jenesis#34]
#### Features
- [x] https://github.com/fetchai/cli/issues/15
- [x] https://github.com/fetchai/cli/issues/30
- [x] https://github.com/fetchai/cli/issues/31
- [x] https://github.com/fetchai/cli/issues/37
- [x] https://github.com/fetchai/cli/issues/32
- [x] https://github.com/fetchai/cli/issues/33

#### Documentation
- [x] https://github.com/fetchai/cli/issues/20

#### Brand
- [x] https://github.com/fetchai/cli/issues/27

#### Landing page launch
- [x] https://github.com/fetchai/cli/issues/19

#### Make repository public
- [x] https://github.com/fetchai/cli/issues/29
