### ISSUE TITLE
Release v0.2.0

### ISSUE THREAD

**Issue by jrriehl** [fetchai/jenesis#39]
- [x] https://github.com/fetchai/cli/issues/11
- [x] https://github.com/fetchai/cli/issues/38
- [x] https://github.com/fetchai/cli/issues/40
- [x] https://github.com/fetchai/jenesis/issues/28
