### ISSUE TITLE
Release v0.3.0

### ISSUE THREAD

**Issue by jrriehl** [fetchai/jenesis#63]
- [x] https://github.com/fetchai/jenesis/issues/48
- [x] https://github.com/fetchai/jenesis/issues/64
- [x] https://github.com/fetchai/jenesis/issues/65
- [x] https://github.com/fetchai/jenesis/issues/74
- [x] https://github.com/fetchai/jenesis/issues/75
